-- Users-Table ----------------------------------
CREATE TABLE public.users (
  id int primary key generated by default as identity,
  username text unique not null,
  password text not null
);

INSERT INTO
  public.users (username, password)
VALUES
  ('user1', 'pass1');

-- Todo-Table ----------------------------------
CREATE TABLE public.todos (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz default null
);

INSERT INTO
  public.todos (task)
VALUES
  ('First entry'),
  ('Second entry');

-- View ----------------------------------

CREATE VIEW public.todo_view AS
SELECT id, done, task, due FROM public.todos
WHERE done = false;

-- Procedures -----------------------------
CREATE PROCEDURE hello_procedure()
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE NOTICE 'Hallo PostgreSQL!';
END;
$$;
