-- Users-Table ----------------------------------
CREATE TABLE public.users (
  id int primary key generated by default as identity,
  username text unique not null,
  password text not null
);

INSERT INTO
  public.users (username, password)
VALUES
  ('user1', 'pass1');

-- Todo-Table ----------------------------------
CREATE TABLE public.todos (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz
);

INSERT INTO
  public.todos (task)
VALUES
  ('First entry'),
  ('Second entry');